### ISSUE TITLE
Bot automatically follows private accounts repeatedly even when follow request is denied

### ISSUE THREAD

**Issue by twilight-sparkle-irl** [gled-rs/mastodon-autofollow#1]
I don't know if this applies to public accounts that softblock it too, but it's still not good and pretty annoying.

**Comment by gled-rs** [comment]
thanks for the report, I need to check how to cope with that and maintain a blacklist of accounts not to follow.

**Comment by gled-rs** [comment]
Can you check that if you block the bot it stops trying to add you ?

**Comment by gled-rs** [comment]
Actually, I don't see any notifications for your refusal on the bot account.

Need to research a bit more how to know you refused, and add you to the blacklist.

**Comment by gled-rs** [comment]
Fix deployed in testing, will commit it later, thanks for the report !

**Comment by gled-rs** [comment]
done and commited
