### ISSUE TITLE
#nobot in account notes ignored

### ISSUE THREAD

**Issue by Fusl** [gled-rs/mastodon-autofollow#15]
It seems the text `#nobot` is ignored by the bot regardless of the script trying to avoid following those users. This is because the note actually contains `#<span>nobot</span>` and we're just checking for the text `#nobot`.

**Comment by Rushyo** [comment]
Details from dupe #16:

> Possibly caused by commit d7075c3?
> 
> I suspect the check might want to be #nobot not in rather than not #nobot in, although I'm not sure how Python handles that.
> 
> (Note my test case, my profile, intentionally uses #nobotancialgardens, to test for the edge-case where somebody has something like "#nobot." in their bio. Probably not relevant, but worth mentioning).
