### ISSUE TITLE
my_id, KeyError:0 - the only thing i get after I run Autofollow.py

### ISSUE THREAD

**Issue by jimmyxrose** [gled-rs/mastodon-autofollow#19]
Hey there! I'm new to Pythone and all these stuff...

I have already automatically created a .pytooter_clientcred.txt with two lines of code
but it didn't create a .pytooter_usercred.txt
and all that i receive is

my_id = mastodon.account_search('botname')[0]['id']
KeyError: 0

-------------
what it might be?

thank you in advance!

**Comment by gled-rs** [comment]
as said in #11 by @Fastidious. Thanks for understanding.

**Comment by jimmyxrose** [comment]
I think i figured it out. Played with the other code, stumbled in an issue, but with different outcome, but i see what i missed in your code to make it work, i guess i'll try tmrrw. Thanks for the cole. Learning this language by practice right now :)
