### ISSUE TITLE
User-level opt out

### ISSUE THREAD

**Issue by Rushyo** [gled-rs/mastodon-autofollow#4]
I have so many follow bots following me right now, even for instances I know I frienderate with :(

It would be nice if the bots respected a common user-level opt out, like leaving them alone when they see #nobot in the user's bio:

"If a user has #nobot in their bio, then that's an indication they want to opt-out of bot activity, and your bot should not be interact[ing] with their profile automatically, except as a result of human-initiated action, as a matter of courtesy.

Not foolproof or universal, but gives bot owners a way to respect users a little better."

**Comment by gled-rs** [comment]
That is actually a good idea.

I'll be glad to accept a pull request in that way, or code it asap.

**Comment by gled-rs** [comment]
Preliminary code commited, thanks for the idea !
