### ISSUE TITLE
expected instance variable in list is out of bounds

### ISSUE THREAD

**Issue by bmbleau** [gled-rs/mastodon-autofollow#5]
When I setup the autofollow bot for my instance it started to choke on my personal account on the same instance when attempting to split the string at the '@' (for checking against blacklisted instances). It produced an IndexError for the index of 1, as it does not exist.

**Comment by arckosfr** [comment]
i have bypassed for test it seems it the index here that block 

```python
for toot in toots:
    if toot['account']['acct'] not in BLACKLIST['users'] and toot['account']['acct'].split('@')[1] not in BLACKLIST['instances']:
        new_user_list.append(toot['account']['id'])
    if len(toot['mentions']) > 0:
        for mention in toot['mentions']:
            if mention['acct'] not in BLACKLIST['users'] and mention['acct'].split('@')[1] not in BLACKLIST['instances']:
                new_user_list.append(mention['id'])
    runparams['since_id'] = toot['id']
```

i have replace 1 by 0 and it work, its a bad workaround but the problem comes from here
oh and the error for the dev : 
```python
Traceback (most recent call last):
  File "Autofollow.py", line 72, in <module>
    if toot['account']['acct'] not in BLACKLIST['users'] and toot['account']['ac                                                                                                   ct'].split('@')[1] not in BLACKLIST['instances']:
IndexError: list index out of range
```

**Comment by gled-rs** [comment]
it's actually because followbot is seeing its own toot. there should be a check if toot['account']['acct'] exists and only process from there. Not near a computer to push the fix though.
